### PR TITLE
28 - add ability to specify custom timeout

### LINKED ISSUE #28: Expose connection timeout
Hi,

We had a problem with HBase cluster https://social.msdn.microsoft.com/Forums/en-US/c6bd04e9-e69b-4e96-b2ef-fa8abcf3bbc3/502-error-in-hbase-cluster?forum=hdinsight and it would take minutes for the client to time out. We would love to reduce the amount of time we need to wait before we know something is wrong.

Thanks

Pawel

### PR DESCRIPTION
**Pull request by pawelpabich**
Fixes #28

### CODE REVIEW

**Comment by thomasjungblut** [comment]
Can you please abstract this as a `RequestOption` class? (Similar to how the Azure SDK is structured). I wanted to add this and some other things that are set per connection in the near future.

Also worth to make it configurable per request instead of globally, e.g. reading might have different timeouts than writing.

**Comment by pawelpabich** [comment]
I would introduce RequestOption class when we have more options. 

@thomasjungblut there is separate timeout for writing and reading and it is actually a single value. Have a look: https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.readwritetimeout(v=vs.110).aspx

Also, personally I would create a new instance of the client if I needed a different timeout.

**Comment by thomasjungblut** [comment]
> I would introduce RequestOption class when we have more options.

That would totally double all the work. We should make it right up-front so it is easier to add new stuff later if needed.
For example, I need keep-alive for specific calls, for others not. Same with tuning Nagle and buffer sizes- which would require tuning the service point. 

> there is a separate timeout for writing and reading and it is actually a single value. 

That's not the same, ReadWriteTimeout is applied on the stream, while Timeout is applied on the TCP states and e.g. on DNS lookups. 

We would also need a client-side timeout that is cancelling the request if it takes too long (so not a stream/connection timeout, but a client-side one).

> Also, personally I would create a new instance of the client if I needed a different timeout.

I don't think that this is good library design at all, but a good work-around.

**Comment by pawelpabich** [comment]
@thomasjungblut this looks to me like a different feature. So what if we get this one in to have something working, and then you can extend it in the future?

**Comment by thomasjungblut** [comment]
@pawelpabich I actually wanted to do it the right way by adding a `RequestOption` that abstracts that parts and add it to all methods. You would make my life much easier by laying the foundation to pass in an "default request option" object through the constructor instead of a hardcoded primitive. 

Let's start with a simple class like

```
class RequestOptions {
 public TimeSpan RequestTimeout { get; set; }
 public ServicePoint CustomServicePoint { get; set; }
}
```

I take it from there.

**Comment by thomasjungblut** [comment]
we can close here, this is superseded by  #45

**Pull request closed without merging**
